### PR TITLE
fix: again click on same tab display same data

### LINKED ISSUE #22: [Bug]: Double click on the same tab [CodingPlateform] content does not displays.
**Problem**
On selecting any coding-platform-name its data gets display but on clicking the same platform again nothing loads.

**To Reproduce**
1. Go to home
2. Click on any plateform **[suppose codeforces]**, it data fetched and displays.
3. Again click on the same button, nothing loads.

**Solution**
On again clicking the same button it should display the same data.

**Screenshot**
Screenshot (70)

### PR DESCRIPTION
**Pull request by Aayushraj22**
**What I have done in this PR:**
fix: #22

The issue has been resolved, now on clicking again to same tab `[ i.e; coding plateform button ]` the data will be displayed without loading for infinte as this was the issue.

**ScreenRecording**

https://github.com/Yash-Parsana/CrazyCoderWebApp/assets/97510973/619a6d5b-8cb8-44c1-a81a-7737f4eee7ed

### CODE REVIEW

**Comment by Yash-Parsana** [comment]
@Aayushraj22 your pr should not remove test.env file

**Comment by Aayushraj22** [comment]
@Yash-Parsana but it was written in md to remove it

**Comment by Aayushraj22** [comment]
@Yash-Parsana  you should assign label to this PR as suggested in the GSSOC guidline otherwise it will not calculated in leaderboard.

**Comment by sanjay-kv** [comment]
@Yash-Parsana let me know if you want to remove the project the engagement seems none in this repo.

**Pull request merged**
